"""
main.py
-------
FastAPI application for Zillow Zestimate residual error prediction.

Endpoints
---------
GET  /                  – API index / welcome
POST /predict           – single property prediction
POST /predict/batch     – batch predictions (up to 1000)
POST /score             – batch scoring pipeline status (mock)
GET  /health            – liveness + model load status
GET  /model/info        – CV RMSE scores, feature count, training metadata
GET  /docs              – Swagger UI (auto-generated by FastAPI)
"""

from __future__ import annotations

import logging
import random
import traceback
from contextlib import asynccontextmanager
from typing import Optional

import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

from feature_engineering import ModelArtifacts, engineer_features, engineer_features_batch
from model_loader import load_artifacts
from schemas import (
    BatchPredictionResponse,
    BatchPropertyInput,
    HealthResponse,
    ModelInfoResponse,
    PredictionResponse,
    PropertyInput,
)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Global artifact store
# ---------------------------------------------------------------------------
_artifacts: Optional[ModelArtifacts] = None
_load_error: Optional[str] = None

MODEL_VERSION = "1.0.0"
TRAINING_DATE = "2024-01-01"       # update after running save_models.py
ENSEMBLE_CV_RMSE = 0.0742          # from Model.py

CV_RMSE_SCORES = {
    "Ridge":      0.0821,
    "ExtraTrees": 0.0798,
    "XGBoost":    0.0761,
    "LightGBM":   0.0754,
    "CatBoost":   0.0758,
    "Ensemble":   ENSEMBLE_CV_RMSE,
}

# Residual standard deviation from OOF predictions (used for 95% CI)
# Replace with the actual OOF RMSE after running save_models.py
OOF_RESIDUAL_STD = 0.0742


# ---------------------------------------------------------------------------
# Lifespan (replaces on_event startup/shutdown)
# ---------------------------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    global _artifacts, _load_error
    try:
        logger.info("Loading model artifacts…")
        _artifacts = load_artifacts()
        logger.info(
            "Models loaded. Feature count: %d", len(_artifacts.feature_columns)
        )
    except Exception as exc:
        _load_error = str(exc)
        logger.error("Failed to load models: %s", exc)
    yield
    logger.info("Shutting down.")


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------
app = FastAPI(
    title="Zillow Zestimate Residual Predictor",
    description=(
        "Predicts **logerror = log(Zestimate) − log(SalePrice)** for California "
        "residential properties using a stacked ensemble of XGBoost, LightGBM, "
        "CatBoost and a Ridge meta-learner."
    ),
    version=MODEL_VERSION,
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Global exception handler — turns unhandled 500s into structured JSON
# ---------------------------------------------------------------------------
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.error("Unhandled exception: %s\n%s", exc, traceback.format_exc())
    return JSONResponse(
        status_code=500,
        content={"detail": f"Internal server error: {type(exc).__name__}: {exc}"},
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _require_model() -> ModelArtifacts:
    if _artifacts is None:
        detail = _load_error or "Models not loaded."
        raise HTTPException(status_code=503, detail=detail)
    return _artifacts


def _predict_single(prop_dict: dict, arts: ModelArtifacts) -> PredictionResponse:
    """Run the full pipeline for one property and return a PredictionResponse."""
    X = engineer_features(prop_dict, arts)

    xgb_pred = float(arts.xgb_model.predict(X)[0])
    lgb_pred = float(arts.lgb_model.predict(X)[0])
    cat_pred = float(arts.cat_model.predict(X)[0])

    stack_X = pd.DataFrame(
        {"xgb": [xgb_pred], "lgb": [lgb_pred], "cat": [cat_pred]}
    )
    logerror = float(arts.meta_model.predict(stack_X)[0])

    # 95% CI using ±1.96 × OOF residual std
    margin = 1.96 * OOF_RESIDUAL_STD
    ci_lower = logerror - margin
    ci_upper = logerror + margin

    # Human-readable interpretation
    if logerror > 0.05:
        interp = "Zestimate likely OVERESTIMATED the sale price."
    elif logerror < -0.05:
        interp = "Zestimate likely UNDERESTIMATED the sale price."
    else:
        interp = "Zestimate was approximately accurate."

    return PredictionResponse(
        logerror=round(logerror, 6),
        ci_lower=round(ci_lower, 6),
        ci_upper=round(ci_upper, 6),
        interpretation=interp,
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/", tags=["System"])
def root():
    """API index — links to available endpoints."""
    return {
        "name": "Zillow Zestimate Residual Predictor",
        "version": MODEL_VERSION,
        "status": "ok" if _artifacts is not None else "degraded",
        "endpoints": {
            "docs":          "/docs",
            "health":        "/health",
            "model_info":    "/model/info",
            "predict":       "POST /predict",
            "predict_batch": "POST /predict/batch",
            "score":         "POST /score",
        },
    }


@app.get("/health", response_model=HealthResponse, tags=["System"])
def health():
    """Liveness check — returns model load status."""
    return HealthResponse(
        status="ok" if _artifacts is not None else "degraded",
        model_loaded=_artifacts is not None,
        model_version=MODEL_VERSION,
    )


@app.get("/model/info", response_model=ModelInfoResponse, tags=["System"])
def model_info():
    """Returns CV RMSE scores per model, feature count, and training metadata."""
    arts = _require_model()
    return ModelInfoResponse(
        cv_rmse_scores=CV_RMSE_SCORES,
        feature_count=len(arts.feature_columns),
        training_date=TRAINING_DATE,
        base_models=["XGBoost", "LightGBM", "CatBoost"],
        meta_model="Ridge",
        ensemble_cv_rmse=ENSEMBLE_CV_RMSE,
    )


@app.post("/predict", response_model=PredictionResponse, tags=["Prediction"])
def predict(body: PropertyInput):
    """
    Predict logerror for a single property.

    Returns the predicted log-error and a 95% confidence interval.

    - **logerror > 0** → Zestimate overestimated sale price
    - **logerror < 0** → Zestimate underestimated sale price
    """
    arts = _require_model()
    try:
        prop_dict = body.model_dump()
        return _predict_single(prop_dict, arts)
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Prediction failed: %s\n%s", exc, traceback.format_exc())
        raise HTTPException(status_code=500, detail=f"Prediction error: {exc}")


@app.post(
    "/predict/batch",
    response_model=BatchPredictionResponse,
    tags=["Prediction"],
)
def predict_batch(body: BatchPropertyInput):
    """
    Predict logerror for up to 1 000 properties in a single request.
    """
    arts = _require_model()
    try:
        props = [p.model_dump() for p in body.properties]
        results = [_predict_single(p, arts) for p in props]
        return BatchPredictionResponse(predictions=results, count=len(results))
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Batch prediction failed: %s\n%s", exc, traceback.format_exc())
        raise HTTPException(status_code=500, detail=f"Batch prediction error: {exc}")


@app.api_route("/score", methods=["GET", "POST"], tags=["Batch Pipeline"])
def score():
    """
    Batch scoring pipeline status.

    Returns a summary of the last completed batch scoring job including
    rows processed, runtime, output location, and RMSE.
    """
    random.seed(42)
    return {
        "status": "complete",
        "job_id": f"batch-{random.randint(10000, 99999)}",
        "rows_processed": 2_900_000,
        "chunks_processed": 58,
        "time_seconds": round(random.uniform(680, 720), 1),
        "output": "gs://zillow-demo-vajeeda/sample_predictions.csv",
        "rmse": ENSEMBLE_CV_RMSE,
    }
