# -*- coding: utf-8 -*-
"""MCDS Review1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zr65XhCirEt0Q_k3un7XeRhCdJUWZNL

# Zillow Zestimate Residual Error Prediction
## Ultimate Hybrid Notebook (Performance + Explainability)

---

## 📌 Problem Statement

Zillow provides a “Zestimate” — an estimated market value of homes.

Our objective is to predict:

logerror = log(Zestimate) − log(SalePrice)

Where:
- Positive logerror → Zestimate overestimated price
- Negative logerror → Zestimate underestimated price

This is a regression problem.

---

## 🎯 Goal of This Notebook

This notebook aims to:

- Perform deep exploratory data analysis
- Engineer meaningful features
- Handle missing data intelligently
- Reduce multicollinearity
- Train multiple advanced models
- Perform cross-validation
- Build an ensemble
- Generate final predictions

This is a hybrid notebook:
✔ Academic clarity
✔ Kaggle-grade performance
✔ Production-ready structure

---

## 📊 Dataset Overview

We are given:

- properties_2016.csv (~2.9M properties)
- train_2016.csv (~90k transactions)
- sample_submission.csv

Counties Included:
- Los Angeles
- Orange County
- Ventura County

---

## 📐 Evaluation Metric

Root Mean Squared Error (RMSE)

Lower RMSE = Better model.

# Data Loading

In this section, we:

1. Import required libraries
2. Load training and property datasets
3. Merge datasets
4. Verify shapes and structure

This forms the foundation of the analysis.
"""

from google.colab import files
files.upload()

import os

# Create Kaggle directory
os.makedirs('/root/.kaggle', exist_ok=True)

# Move kaggle.json
!mv kaggle.json /root/.kaggle/

# Secure permissions
!chmod 600 /root/.kaggle/kaggle.json

print("Kaggle API configured successfully.")

!pip install --upgrade kaggle -q

!kaggle competitions list

!kaggle competitions download -c zillow-prize-1

!unzip -q zillow-prize-1.zip
print("Dataset unzipped.")

!free -h

# =========================================================
# 02 - DATA LOADING
# =========================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Loading train dataset...")
train = pd.read_csv(
    "train_2016_v2.csv",
    parse_dates=["transactiondate"]
)

print("Loading properties dataset with optimized dtypes...")

dtype_dict = {
    "parcelid": "Int32",
    "bathroomcnt": "float32",
    "bedroomcnt": "float32",
    "calculatedfinishedsquarefeet": "float32",
    "finishedsquarefeet12": "float32",
    "fips": "Int16",
    "latitude": "float32",
    "longitude": "float32",
    "lotsizesquarefeet": "float32",
    "taxamount": "float32",
    "taxvaluedollarcnt": "float32",
    "structuretaxvaluedollarcnt": "float32",
    "landtaxvaluedollarcnt": "float32",
    "yearbuilt": "float32"
}

properties = pd.read_csv(
    "properties_2016.csv",
    dtype=dtype_dict,
    low_memory=False
)

print("Datasets loaded successfully.")

for col in properties.select_dtypes(include=["object"]).columns:
    properties[col] = properties[col].astype("category")

print("Converted object columns to category.")

print("Properties memory usage:")
properties.info(memory_usage='deep')

# ------------------------------------------------
# Drop useless columns from properties early
# ------------------------------------------------

missing_ratio = properties.isnull().mean()

cols_drop = missing_ratio[missing_ratio > 0.95].index.tolist()

properties.drop(columns=cols_drop, inplace=True)

print("Dropped high-missing property columns:", len(cols_drop))

df = train.merge(properties, on="parcelid", how="left")
for col in df.select_dtypes(include=["float64"]).columns:
    df[col] = df[col].astype("float32")

print("Converted float64 → float32")
print("Merged dataset shape:", df.shape)

print("Memory after merge:")
df.info(memory_usage='deep')

"""# Data Overview & Initial Exploration

In this section, we:

- Examine data types
- Check unique values
- Explore target variable
- Understand distribution patterns
- Detect obvious issues
"""

# =========================================================
# 03 - DATA OVERVIEW
# =========================================================

# -------------------------------
# Check Data Types
# -------------------------------
"""
Understanding datatypes helps us:
- Identify categorical vs numeric features
- Plan encoding strategy
"""

dtype_summary = df.dtypes.value_counts()
print(dtype_summary)

# -------------------------------
# Target Variable Analysis
# -------------------------------
"""
We analyze distribution of logerror.
Outliers can heavily impact RMSE.
"""

plt.figure(figsize=(10,5))
sns.histplot(df["logerror"], bins=100, kde=True)
plt.title("Distribution of logerror")
plt.show()

# -------------------------------
# Outlier Clipping
# -------------------------------
"""
We clip extreme 1% tails to stabilize training.
"""

upper_limit = np.percentile(df["logerror"], 99)
lower_limit = np.percentile(df["logerror"], 1)

df["logerror"] = np.clip(df["logerror"], lower_limit, upper_limit)

plt.figure(figsize=(10,5))
sns.histplot(df["logerror"], bins=100, kde=True)
plt.title("Clipped logerror Distribution")
plt.show()

"""# Missing Value Analysis

The Zillow dataset contains a very large number of missing values.

Proper missing value handling is critical because:

- Blind imputation can introduce bias
- Some features are almost entirely missing
- Some missingness itself may be informative

In this section we will:

1. Calculate missing percentage per column
2. Remove features with extreme missingness (>90%)
3. Separate numeric and categorical columns
4. Prepare for intelligent imputation
"""

# =========================================================
# 04 - MISSING VALUE ANALYSIS
# =========================================================

# -------------------------------
# Calculate Missing Percentage
# -------------------------------
"""
We compute percentage of missing values per column.
"""

missing_percentage = df.isnull().mean().sort_values(ascending=False)

missing_df = pd.DataFrame({
    "column": missing_percentage.index,
    "missing_percentage": missing_percentage.values
})

missing_df.head(15)

# -------------------------------
# Visualize Top Missing Columns
# -------------------------------
"""
Visual inspection helps identify extreme sparsity.
"""

plt.figure(figsize=(10,8))
sns.barplot(
    x="missing_percentage",
    y="column",
    data=missing_df.head(20)
)
plt.title("Top 20 Columns by Missing Percentage")
plt.show()

# -------------------------------
# Drop Extremely Sparse Features
# -------------------------------
"""
We drop features with > 90% missing values.
These provide very little predictive power.
"""

threshold = 0.90

cols_to_drop = missing_df[missing_df["missing_percentage"] > threshold]["column"].tolist()

print("Dropping", len(cols_to_drop), "columns with >90% missing")

df = df.drop(columns=cols_to_drop)

print("New Shape:", df.shape)

# -------------------------------
# Separate Numeric & Categorical
# -------------------------------
"""
We separate columns to plan imputation strategy.
"""

numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()

print("Numeric Columns:", len(numeric_cols))
print("Categorical Columns:", len(categorical_cols))

"""# Intelligent Imputation Strategy

Instead of blindly filling missing values:

- Numeric features → median (robust to skew)
- Categorical features → mode
- Add missing indicator columns

Why median?
Because Zillow data contains heavy skew and extreme values.

We also create missing indicator flags for high-impact features.
"""

# =========================================================
# 05 - IMPUTATION STRATEGY
# =========================================================

# -------------------------------
# Add Missing Indicators
# -------------------------------
"""
For columns with 10–40% missing values,
missingness itself may carry signal.
"""

for col in df.columns:
    missing_ratio = df[col].isnull().mean()

    if 0.10 < missing_ratio < 0.40:
        df[col + "_missing_flag"] = df[col].isnull().astype(int)

print("Missing indicators added.")
train_missing_flags = [col for col in df.columns if col.endswith("_missing_flag")]

# -------------------------------
# Impute Numeric Features
# -------------------------------
"""
Median imputation is more stable for skewed real estate data.
"""

for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].median(), inplace=True)

print("Numeric imputation complete.")

# -------------------------------
# Impute Categorical Features
# -------------------------------
"""
Mode imputation for categorical columns.
"""

for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].mode()[0], inplace=True)

print("Categorical imputation complete.")

# Final Missing Check
print("Remaining missing values:", df.isnull().sum().sum())

"""# Advanced Feature Engineering

Feature engineering is the single most important step.

We create:

1. Property age features
2. Tax-based ratios
3. Area efficiency ratios
4. Bathroom combinations
5. Time-based features
6. Interaction features

These engineered variables often outperform raw features.
"""

# =========================================================
# 06 - FEATURE ENGINEERING
# =========================================================

# -------------------------------
# Property Age
# -------------------------------
"""
Newer homes tend to have smaller prediction errors.
"""

df["transaction_year"] = df["transactiondate"].dt.year
df["property_age"] = df["transaction_year"] - df["yearbuilt"]

df["property_age"].fillna(df["property_age"].median(), inplace=True)

# -------------------------------
# Total Bathrooms
# -------------------------------
"""
Combine full + 0.75 baths.
"""

if "threequarterbathnbr" in df.columns:
    df["total_bath"] = (
        df.get("fullbathcnt", 0)
        + 0.75 * df.get("threequarterbathnbr", 0)
    )

# -------------------------------
# Tax Ratios
# -------------------------------
"""
Tax ratios are highly predictive.
"""

df["tax_ratio"] = df["taxamount"] / (df["taxvaluedollarcnt"] + 1)
df["structure_land_ratio"] = df["structuretaxvaluedollarcnt"] / (df["landtaxvaluedollarcnt"] + 1)

# -------------------------------
# Area Efficiency
# -------------------------------
"""
How efficiently lot space is used.
"""

df["living_area_ratio"] = df["calculatedfinishedsquarefeet"] / (df["lotsizesquarefeet"] + 1)

# -------------------------------
# Time Features
# -------------------------------
"""
Seasonal patterns exist in transactions.
"""

df["transaction_month"] = df["transactiondate"].dt.month
df["transaction_quarter"] = df["transactiondate"].dt.quarter
df["transaction_dayofweek"] = df["transactiondate"].dt.dayofweek

# -------------------------------
# Cyclical Encoding for Month
# -------------------------------
"""
Encodes month cyclically (important for tree + linear models).
"""

df["month_sin"] = np.sin(2 * np.pi * df["transaction_month"] / 12)
df["month_cos"] = np.cos(2 * np.pi * df["transaction_month"] / 12)

print("Feature Engineering Complete.")
print("Current Shape:", df.shape)

"""# Advanced Spatial Feature Engineering

Location is one of the strongest signals in real estate.

We will engineer:

1. Normalized latitude & longitude
2. Spatial clustering using KMeans
3. Regional density features
4. County extraction (from FIPS)
5. Region-based statistical aggregations

Why?

Because raw latitude & longitude do not capture neighborhood structure.
Clustering allows the model to learn local pricing behavior.
"""

# =========================================================
# 07 - SPATIAL FEATURE ENGINEERING
# =========================================================

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# -------------------------------
# Normalize Latitude & Longitude
# -------------------------------
"""
Latitude & longitude values are large numbers.
We scale them before clustering.
"""

# Zillow latitude & longitude are scaled by 1e6
df["latitude"] = df["latitude"] / 1e6
df["longitude"] = df["longitude"] / 1e6

# -------------------------------
# Spatial Clustering (TRAIN)
# -------------------------------

geo_scaler = StandardScaler()

geo_scaled = geo_scaler.fit_transform(
    df[["latitude", "longitude"]]
)

kmeans = KMeans(
    n_clusters=20,      # or whatever you used
    random_state=42
)

df["geo_cluster"] = kmeans.fit_predict(geo_scaled)

print("Geo normalization complete.")

# -------------------------------
# KMeans Clustering
# -------------------------------
"""
We create spatial clusters.
This captures neighborhood-level pricing behavior.
"""

# Choosing 25 clusters (balanced complexity)
kmeans = KMeans(n_clusters=25, random_state=42, n_init=10)

df["geo_cluster"] = kmeans.fit_predict(geo_scaled)

print("Spatial clustering complete.")
df["geo_cluster"].value_counts().head()

# -------------------------------
# Geo Density Feature
# -------------------------------
"""
Number of properties in each cluster.
Captures area popularity / density.
"""

cluster_density = df["geo_cluster"].value_counts().to_dict()

df["geo_cluster_density"] = df["geo_cluster"].map(cluster_density)

print("Geo density feature created.")

# -------------------------------
# County Feature from FIPS
# -------------------------------
"""
FIPS code identifies county.
6037 = Los Angeles
6059 = Orange
6111 = Ventura
"""

df["county"] = df["fips"].astype(str)

print(df["county"].value_counts())

# -------------------------------
# Cluster-Level Aggregation
# -------------------------------
"""
Mean tax value per cluster.
Mean finished area per cluster.
"""

cluster_agg = df.groupby("geo_cluster").agg({
    "taxvaluedollarcnt": "mean",
    "calculatedfinishedsquarefeet": "mean"
}).rename(columns={
    "taxvaluedollarcnt": "cluster_mean_tax",
    "calculatedfinishedsquarefeet": "cluster_mean_area"
})

df = df.merge(cluster_agg, on="geo_cluster", how="left")

print("Cluster aggregation features added.")

# -------------------------------
# Geo Interaction Feature
# -------------------------------

# Ensure property_age exists
df["property_age"] = 2016 - df["yearbuilt"]

df["age_cluster_interaction"] = (
    df["property_age"] * df["geo_cluster"]
)

print("Spatial feature engineering complete.")
print("Current Shape:", df.shape)

# =========================================================
# 12 - CROSS VALIDATED TARGET ENCODING
# =========================================================

from sklearn.model_selection import KFold

def target_encode_cv(df, column, target, n_splits=5):

    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
    encoded = pd.Series(index=df.index, dtype=float)

    for train_idx, val_idx in kf.split(df):

        train_data = df.iloc[train_idx]
        val_data = df.iloc[val_idx]

        means = train_data.groupby(column)[target].mean()

        encoded.iloc[val_idx] = val_data[column].map(means)

    return encoded

# Apply target encoding

df["geo_cluster_te"] = target_encode_cv(df, "geo_cluster", "logerror")
df["county_te"] = target_encode_cv(df, "county", "logerror")

print("Target encoding added.")

# Save global encodings for test use

geo_cluster_means = df.groupby("geo_cluster")["logerror"].mean()
county_means = df.groupby("county")["logerror"].mean()

"""# Multicollinearity Reduction

Highly correlated features:

- Make linear models unstable
- Inflate variance
- Increase model complexity

We will:

1. Compute correlation matrix
2. Drop highly correlated (>0.95) features
3. Calculate Variance Inflation Factor (VIF)
4. Remove problematic variables

This ensures model stability and better generalization.
"""

# =========================================================
# 08 - MULTICOLLINEARITY REDUCTION
# =========================================================

# -------------------------------
# Correlation Matrix
# -------------------------------

corr_matrix = df.select_dtypes(include=[np.number]).corr().abs()

upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

high_corr_features = [
    column for column in upper.columns
    if any(upper[column] > 0.95)
]

print("Highly correlated features:", len(high_corr_features))

df.drop(columns=high_corr_features, inplace=True)

print("After correlation removal:", df.shape)

# -------------------------------
# VIF Calculation
# -------------------------------

from statsmodels.stats.outliers_influence import variance_inflation_factor

numeric_features = df.select_dtypes(include=[np.number]).drop(columns=["logerror"])

X_numeric = numeric_features.astype("float64").fillna(0)

vif_data = pd.DataFrame()
vif_data["feature"] = X_numeric.columns
vif_data["VIF"] = [
    variance_inflation_factor(X_numeric.values, i)
    for i in range(X_numeric.shape[1])
]

# Drop extremely high VIF features
high_vif = vif_data[vif_data["VIF"] > 20]["feature"].tolist()

print("High VIF features:", len(high_vif))

df.drop(columns=high_vif, inplace=True)

print("Final Shape after VIF:", df.shape)

target = "logerror"

drop_cols = ["logerror", "parcelid", "transactiondate"]

X = df.drop(columns=drop_cols)
y = df[target]

print("Final feature shape:", X.shape)

"""# Baseline Modeling

Before jumping into complex boosting models, we establish strong baselines.

Why?

Because:
- It tells us if feature engineering is working
- It prevents overfitting illusions
- It gives us a benchmark RMSE

We will train:

1. Ridge Regression (linear baseline)
2. ExtraTrees Regressor (tree baseline)

Using:
- 5-Fold Cross Validation
- RMSE evaluation
"""

# =========================================================
# 09 - BASELINE MODELING
# =========================================================

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Ridge
from sklearn.ensemble import ExtraTreesRegressor

# -------------------------------
# Prepare X and y
# -------------------------------

print("Feature Matrix Shape:", X.shape)

# -------------------------------
# KFold Setup
# -------------------------------

kf = KFold(n_splits=5, shuffle=True, random_state=42)

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

# -------------------------------
# Ridge Regression (Memory Safe)
# -------------------------------

X_linear = X.select_dtypes(include=[np.number])

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_linear = pd.DataFrame(
    scaler.fit_transform(X_linear),
    columns=X_linear.columns,
    index=X_linear.index
)

ridge_model = Ridge(alpha=1.0)
ridge_scores = []

for train_idx, val_idx in kf.split(X_linear):

    X_train, X_val = X_linear.iloc[train_idx], X_linear.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    ridge_model.fit(X_train, y_train)
    preds = ridge_model.predict(X_val)

    score = rmse(y_val, preds)
    ridge_scores.append(score)

print("Ridge CV RMSE:", np.mean(ridge_scores))

# -------------------------------
# ExtraTrees Regressor (Fixed)
# -------------------------------

X_tree = X.select_dtypes(include=[np.number])

et_model = ExtraTreesRegressor(
    n_estimators=200,
    max_depth=None,
    min_samples_split=5,
    n_jobs=-1,
    random_state=42
)

et_scores = []

for train_idx, val_idx in kf.split(X_tree):

    X_train, X_val = X_tree.iloc[train_idx], X_tree.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    et_model.fit(X_train, y_train)
    preds = et_model.predict(X_val)

    score = rmse(y_val, preds)
    et_scores.append(score)

print("ExtraTrees CV RMSE:", np.mean(et_scores))

"""# Advanced Boosting Models

Boosting models typically dominate structured tabular competitions.

We will train:

1. XGBoost
2. LightGBM
3. CatBoost

Using:
- Balanced hyperparameters
- 5-Fold CV
- Early stopping

These models handle:
- Non-linear relationships
- Feature interactions
- Missing values
- High dimensional data
"""

# Install libraries (run once in Colab)

!pip install xgboost lightgbm catboost -q

import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostRegressor

# -------------------------------
# XGBoost (Fixed)
# -------------------------------

X_xgb = X.select_dtypes(include=[np.number])

xgb_scores = []

for train_idx, val_idx in kf.split(X_xgb):

    X_train, X_val = X_xgb.iloc[train_idx], X_xgb.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = xgb.XGBRegressor(**xgb_params)

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False
    )

    preds = model.predict(X_val)
    score = rmse(y_val, preds)
    xgb_scores.append(score)

print("XGBoost CV RMSE:", np.mean(xgb_scores))

# -------------------------------
# LightGBM
# -------------------------------

lgb_params = {
    "learning_rate": 0.05,
    "max_depth": -1,
    "num_leaves": 64,
    "n_estimators": 500,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "random_state": 42
}

lgb_scores = []
X_lgb = X.select_dtypes(include=[np.number])
for train_idx, val_idx in kf.split(X_lgb):

    X_train, X_val = X_lgb.iloc[train_idx], X_lgb.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = lgb.LGBMRegressor(**lgb_params)
    model.fit(X_train, y_train)

    preds = model.predict(X_val)
    score = rmse(y_val, preds)
    lgb_scores.append(score)

print("LightGBM CV RMSE:", np.mean(lgb_scores))

# -------------------------------
# CatBoost (Numeric-Only Version)
# -------------------------------

X_cat = X.select_dtypes(include=[np.number])

cat_scores = []

for train_idx, val_idx in kf.split(X_cat):

    X_train, X_val = X_cat.iloc[train_idx], X_cat.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = CatBoostRegressor(
        iterations=500,
        learning_rate=0.05,
        depth=8,
        loss_function="RMSE",
        verbose=False,
        random_state=42
    )

    model.fit(X_train, y_train)

    preds = model.predict(X_val)
    score = rmse(y_val, preds)
    cat_scores.append(score)

print("CatBoost CV RMSE:", np.mean(cat_scores))

# =========================================================
# PREPARE CLEAN MODEL MATRICES (DO THIS ONCE)
# =========================================================

X_full = df.drop(columns=["logerror"])
y = df["logerror"]

# Numeric-only matrix for XGB / LGB / sklearn models
X_numeric = X_full.select_dtypes(include=[np.number]).copy()

print("Full shape:", X_full.shape)
print("Numeric shape:", X_numeric.shape)

"""# Ensemble and Final Prediction

Ensembling multiple strong models usually improves performance.

We will:

1. Train full models on entire dataset
2. Generate predictions
3. Weighted average ensemble
4. Prepare submission file

This increases stability and reduces variance.
"""

# -------------------------------
# Train Final Models (FIXED)
# -------------------------------

final_xgb = xgb.XGBRegressor(**xgb_params)
final_lgb = lgb.LGBMRegressor(**lgb_params)
final_cat = CatBoostRegressor(
    iterations=500,
    learning_rate=0.05,
    depth=8,
    loss_function="RMSE",
    verbose=False
)

# Train on numeric matrix only
final_xgb.fit(X_numeric, y)
final_lgb.fit(X_numeric, y)
final_cat.fit(X_numeric, y)

print("Final models trained.")

"""# Cross-Validated Target Encoding

Categorical variables such as:

- geo_cluster
- county

can carry strong signal.

Instead of one-hot encoding, we replace them with:

Mean logerror per category

BUT carefully — using cross-validation to prevent data leakage.

This improves predictive power while staying robust.

# Bayesian Hyperparameter Tuning

Instead of manually choosing parameters,
we use Optuna to:

- Search intelligently
- Minimize RMSE
- Optimize model performance

This avoids random guessing.
"""

X_full = df.drop(columns=["logerror"])
y = df["logerror"]

X_numeric = X_full.select_dtypes(include=[np.number]).copy()

# Install Optuna
!pip install optuna -q

import optuna
from sklearn.model_selection import cross_val_score

# =========================================================
# Bayesian tuning for LightGBM
# =========================================================

def objective(trial):

    params = {
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1),
        "num_leaves": trial.suggest_int("num_leaves", 20, 100),
        "max_depth": trial.suggest_int("max_depth", -1, 12),
        "n_estimators": 500,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "random_state": 42
    }

    model = lgb.LGBMRegressor(**params)

    scores = cross_val_score(
        model,
        X_numeric,   # ✅ FIXED
        y,
        cv=5,
        scoring="neg_root_mean_squared_error",
        n_jobs=-1
    )

    return -scores.mean()

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=20)

best_lgb_params = study.best_params
print("Best Params:", best_lgb_params)

"""# Out-of-Fold Stacking

We generate OOF predictions from:

- XGBoost
- LightGBM
- CatBoost

Then train a meta-model on these predictions.

This allows the meta-model to learn:
Which base model performs better under which conditions.
"""

# =========================================================
# 14 - OUT OF FOLD STACKING (FIXED)
# =========================================================

# Use numeric-only matrix
X_stack = X_numeric

oof_xgb = np.zeros(len(X_stack))
oof_lgb = np.zeros(len(X_stack))
oof_cat = np.zeros(len(X_stack))

kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_idx, val_idx in kf.split(X_stack):

    X_train, X_val = X_stack.iloc[train_idx], X_stack.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    xgb_model = xgb.XGBRegressor(**xgb_params)
    lgb_model = lgb.LGBMRegressor(**best_lgb_params)
    cat_model = CatBoostRegressor(
        iterations=400,
        learning_rate=0.05,
        depth=8,
        loss_function="RMSE",
        verbose=False
    )

    xgb_model.fit(X_train, y_train)
    lgb_model.fit(X_train, y_train)
    cat_model.fit(X_train, y_train)

    oof_xgb[val_idx] = xgb_model.predict(X_val)
    oof_lgb[val_idx] = lgb_model.predict(X_val)
    oof_cat[val_idx] = cat_model.predict(X_val)

# Meta-model

stack_X = pd.DataFrame({
    "xgb": oof_xgb,
    "lgb": oof_lgb,
    "cat": oof_cat
})

meta_model = Ridge(alpha=1.0)
meta_model.fit(stack_X, y)

print("Stacking complete.")

"""# SHAP Explainability

SHAP explains:

- Which features increase error
- Which decrease error
- Global importance ranking

This makes our model interpretable.
"""

!pip install shap -q

import shap

# Use numeric matrix (same used to train final_xgb)
sample_X = X_numeric.sample(2000, random_state=42)

explainer = shap.TreeExplainer(final_xgb)
shap_values = explainer.shap_values(sample_X)

shap.summary_plot(shap_values, sample_X)

"""# Model Comparison Dashboard

We visualize:

- CV RMSE comparison
- Feature importance
- Residual distribution
- Ensemble performance
"""

# RMSE comparison

model_scores = {
    "Ridge": np.mean(ridge_scores),
    "ExtraTrees": np.mean(et_scores),
    "XGBoost": np.mean(xgb_scores),
    "LightGBM": np.mean(lgb_scores),
    "CatBoost": np.mean(cat_scores)
}

plt.figure(figsize=(10,6))
sns.barplot(x=list(model_scores.keys()), y=list(model_scores.values()))
plt.title("Model Comparison (CV RMSE)")
plt.xticks(rotation=45)
plt.show()

# =========================================================
# CREATE TEST DATASET
# =========================================================

sample_submission = pd.read_csv("sample_submission.csv")

test_df = properties.merge(
    sample_submission[["ParcelId"]],
    left_on="parcelid",
    right_on="ParcelId",
    how="inner"
)

test_df.drop(columns=["ParcelId"], inplace=True)


# =========================================================
# APPLY SAME FEATURE ENGINEERING AS TRAIN
# =========================================================

# ---- Time Features ----
test_df["transaction_year"] = 2016
test_df["transaction_month"] = 10
test_df["transaction_quarter"] = 4
test_df["transaction_dayofweek"] = 0

test_df["property_age"] = 2016 - test_df["yearbuilt"]

# Cyclical Encoding
test_df["month_sin"] = np.sin(2 * np.pi * test_df["transaction_month"] / 12)
test_df["month_cos"] = np.cos(2 * np.pi * test_df["transaction_month"] / 12)

# ---- Ratios ----
test_df["tax_ratio"] = test_df["taxamount"] / (test_df["taxvaluedollarcnt"] + 1)
test_df["structure_land_ratio"] = (
    test_df["structuretaxvaluedollarcnt"] /
    (test_df["landtaxvaluedollarcnt"] + 1)
)
test_df["living_area_ratio"] = (
    test_df["calculatedfinishedsquarefeet"] /
    (test_df["lotsizesquarefeet"] + 1)
)

# =========================================================
# GEO PROCESSING (FIXED VERSION)
# =========================================================

# Normalize
test_df["latitude"] = test_df["latitude"] / 1e6
test_df["longitude"] = test_df["longitude"] / 1e6

# 🔥 IMPORTANT: Fill NaNs BEFORE clustering (use TRAIN median)
geo_medians = df[["latitude", "longitude"]].median()

test_df[["latitude", "longitude"]] = (
    test_df[["latitude", "longitude"]]
    .fillna(geo_medians)
)

# Scale using TRAIN scaler
test_geo_scaled = geo_scaler.transform(
    test_df[["latitude", "longitude"]]
)

# Predict cluster using TRAIN kmeans
test_df["geo_cluster"] = kmeans.predict(test_geo_scaled)


# =========================================================
# COUNTY + TARGET ENCODING
# =========================================================

test_df["county"] = test_df["fips"].astype(str)

global_mean = y.mean()

test_df["geo_cluster_te"] = (
    test_df["geo_cluster"]
    .map(geo_cluster_means)
    .fillna(global_mean)
)

test_df["county_te"] = (
    test_df["county"]
    .map(county_means)
    .fillna(global_mean)
)

# Cluster aggregation
test_df = test_df.merge(cluster_agg, on="geo_cluster", how="left")

# Additional features
test_df["geo_cluster_density"] = (
    test_df["geo_cluster"]
    .map(cluster_density)
)

test_df["age_cluster_interaction"] = (
    test_df["property_age"] * test_df["geo_cluster"]
)

if "threequarterbathnbr" in test_df.columns:
    test_df["total_bath"] = (
        test_df.get("fullbathcnt", 0) +
        0.75 * test_df.get("threequarterbathnbr", 0)
    )


# =========================================================
# APPLY SAME MISSING HANDLING
# =========================================================

# Missing Flags
for col in train_missing_flags:
    base_col = col.replace("_missing_flag", "")
    if base_col in test_df.columns:
        test_df[col] = test_df[base_col].isnull().astype(int)

# 🔥 Numeric imputation using TRAIN medians (not test medians)
train_numeric_medians = df.median(numeric_only=True)

for col in test_df.select_dtypes(include=[np.number]).columns:
    if col in train_numeric_medians:
        test_df[col] = test_df[col].fillna(train_numeric_medians[col])

# Categorical imputation using TRAIN modes
for col in test_df.select_dtypes(include=["object", "category"]).columns:
    if col in df.columns:
        mode_val = df[col].mode()[0] if col in df and not df[col].mode().empty else "Unknown"
        test_df[col] = test_df[col].fillna(mode_val)


# =========================================================
# DROP MULTICOLLINEAR FEATURES
# =========================================================

test_df.drop(columns=high_corr_features, inplace=True, errors="ignore")
test_df.drop(columns=high_vif, inplace=True, errors="ignore")


# =========================================================
# ALIGN STRICTLY WITH TRAINING FEATURE SPACE
# =========================================================

# Add any missing columns from training
for col in X_numeric.columns:
    if col not in test_df.columns:
        test_df[col] = 0

# Keep exact same order
X_test = test_df[X_numeric.columns].copy()

# Ensure dtype consistency
for col in X_test.columns:
    if X_test[col].dtype == "float64":
        X_test[col] = X_test[col].astype("float32")

# Final safety check
assert list(X_test.columns) == list(X_numeric.columns)


# =========================================================
# PREDICT
# =========================================================

xgb_test = final_xgb.predict(X_test)
lgb_test = final_lgb.predict(X_test)
cat_test = final_cat.predict(X_test)

stack_test = pd.DataFrame({
    "xgb": xgb_test,
    "lgb": lgb_test,
    "cat": cat_test
})

test_preds = meta_model.predict(stack_test)


# =========================================================
# CREATE SUBMISSION
# =========================================================

sample_submission["201610"] = test_preds
sample_submission["201611"] = test_preds
sample_submission["201612"] = test_preds

sample_submission.to_csv("final_submission.csv", index=False)

print("Final submission saved.")